version: '3.6'
services:
  app:
    image: openjdk:11
    container_name: app
    ports:
      - 8080:8080
    tty: true
    volumes:
      - .:/srv:cached
    working_dir: /srv
    depends_on:
      - db

  adminer:
    image: adminer:4.7.8
    container_name: adminer
    ports:
      - "9000:8080"
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p4w0rd"
      POSTGRES_DB: "bookmemo4444"
    ports:
      - "5432:5432"
    volumes:
      - dbvol:/var/lib/postgresql/data

volumes:
  dbvol: