version: "3.9"

services:
  app:
    build: 
      context: .
    tty: true
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - type: bind
        source: .
        target: /srv:cached
    working_dir: /srv
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - type: volume
        source: dbvol
        target: /var/lib/postgresql/data

volumes:
  dbvol:
