version: "3.9"

services:
  app:
    build: 
      context: .
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - type: bind
        source: .
        target: /srv:cached
    working_dir: /srv
    command: bash -c "./gradlew bootRun"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - type: volume
        source: dbvol
        target: /var/lib/postgresql/data

volumes:
  dbvol: