version: '3.6'
services:
  app:
    build: .
    container_name: app
    ports:
      - 8080:8080
    tty: true
    volumes:
      - .:/srv:cached
    working_dir: /srv
    command: bash -c "./gradlew build && ./gradlew bootRun"
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p4w0rd"
      POSTGRES_DB: "bookmemo"
    ports:
      - "5432:5432"
    volumes:
      - dbvol:/var/lib/postgresql/data

volumes:
  dbvol: