#デプロイ時に変更
spring:
  #本番
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${DB_URL}
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: embedded
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      table-name: SPRING_SESSION
    timeout: 1800    
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.jdbc.time_zone]': Asia/Tokyo
  h2:
    console:
      enabled: false
  thymeleaf:
    cache: true
  devtools:
    restart:
      enabled: false
  management:
    server:
      port: 80
    endpoints:
      web:
        exposure:
        include: "*"
        exclude: "env,beans,info,health,shutdown"
    