INSERT INTO roles (authority) values ('ROLE_ADMIN');
INSERT INTO roles (authority) values ('ROLE_USER');

INSERT INTO accounts (account_name,account_email,account_password) values ('aaa','aaa@example.com','$2a$10$d8DVzpGAp5Pexvf6c3Whi./ZMVcT1gAWHXeFM.jZBhvfxhyToFa0e');
INSERT INTO account_role values (1,2);
INSERT INTO accounts (account_name,account_email,account_password) values ('aa','arai@example.com','$2a$10$d8DVzpGAp5Pexvf6c3Whi./ZMVcT1gAWHXeFM.jZBhvfxhyToFa0e');
INSERT INTO account_role values (2,1);
INSERT INTO accounts (account_name,account_email,account_password) values ('dd','ddd@example.com','$2a$10$hC3v6TZOLwSNPzrgNl5y9.G1tP3Owd6AySTWHSAc4eNBpXCAhunKO');
INSERT INTO account_role values (3,2);
INSERT INTO accounts (account_name,account_email,account_password) values ('bb','bbb@example.com','$2a$10$FhgQMKCtStjHL.Jkoo9LWOI9yy..lgHQHjzmax5/rQz2k6C.QU5Ui');
INSERT INTO account_role values (4,2);

INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title1','内容1','カテゴリ1','本1',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title2','内容2','カテゴリ2','本2',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title3','内容3','カテゴリ3','本3',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title4','内容4','カテゴリ4','本4',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title5','内容5','カテゴリ1','本5',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title6','内容6','カテゴリ2','本6',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title7','内容7','カテゴリ3','本7',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title8','内容8','カテゴリ4','本8',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title9','内容9','カテゴリ1','本9',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title10','内容10','カテゴリ2','本10',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title11','内容11','カテゴリ3','本11',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title12','内容12','カテゴリ4','本12',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title13','内容13','カテゴリ1','本13',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title14','内容14','カテゴリ2','本14',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title15','内容15','カテゴリ3','本15',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title16','内容16','カテゴリ4','本16',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title17','内容17','カテゴリ1','本17',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title18','内容18','カテゴリ2','本18',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title19','内容19','カテゴリ3','本19',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title20','内容20','カテゴリ4','本20',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title21','内容21','カテゴリ1','本21',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title22','内容22','カテゴリ2','本22',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title23','内容23','カテゴリ3','本23',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title24','内容24','カテゴリ4','本24',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title25','内容25','カテゴリ1','本25',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title26','内容26','カテゴリ2','本26',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title27','内容27','カテゴリ3','本27',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title28','内容28','カテゴリ4','本28',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title29','内容29','カテゴリ1','本29',4);
