INSERT INTO roles (authority) values ('ROLE_ADMIN');
INSERT INTO roles (authority) values ('ROLE_USER');

INSERT INTO accounts (account_name,account_email,account_password) values ('sample','sample@example.com','$2a$10$DuK1iIwr/GvzJ2i//U1lHeyOj/1AxGaX08bbkYmCpBapHmxyHNRJK');
INSERT INTO account_role values (1,2);
INSERT INTO accounts (account_name,account_email,account_password) values ('arairyo','arairyo@example.com','$2a$10$DuK1iIwr/GvzJ2i//U1lHeyOj/1AxGaX08bbkYmCpBapHmxyHNRJK');
INSERT INTO account_role values (2,1);
INSERT INTO accounts (account_name,account_email,account_password) values ('user','user@example.com','$2a$10$DuK1iIwr/GvzJ2i//U1lHeyOj/1AxGaX08bbkYmCpBapHmxyHNRJK');
INSERT INTO account_role values (3,2);
INSERT INTO accounts (account_name,account_email,account_password) values ('test','testtest@example.com','$2a$10$JRG0ei8wKNaCgJPzA2RPu.fX.vB52s.LB8aHW4CwMC1NmDU/vJY9i');
INSERT INTO account_role values (4,2);

INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('独習Gitを読んで','git push origin main','Git','独習Git',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('サーバーサイドJavaプログラミング','Reqest Response','JavaEE','サーバサイドJava',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('Gof','singleton','デザインパターン','GoF本',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('OO','Object指向','OO','OO入門',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('安全なWebアプリケーションの作り方','IPAに資料がある｡','セキュリティ','徳丸本',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('チャート式','内容6','数学','本6',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('ルビー','gem','ruby','Effective Ruby',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('title8','hello world','python','Effective Python',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('java','sysout','java','Effective Java',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('C++','print','C++','Effective C++',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('C#','wpf','C#','Effective C#',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('TCP','1270001','TCPIP','詳解TCPIP',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('若葉ちゃんGit','git pull origin main','Git','若葉ちゃんGit',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('Bootstrap便利','内容14','Bootstrap','Bootstrap入門',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('Gatsby使えるようになりたい','リアクトは....','react','本15',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('ああああ','react www','react','react入門',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('ビュー','vvvv','vue','Vue入門',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('びゅー','v-if','vue','Vue入門',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('びゅー','v-on','vue','Vue入門',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('りあくと','りあくとおお0','react','reach hook',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('vue','v-model','vue','Vue入門続',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('hibernate','まっぴんぐー','spring','hibernate',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('security','沼','spring','spring security',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('VBA','excelかたかた','vba','Excel',4);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('GAS','email自動化','gas','Google',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('いんふらー','サーバ管理は大変','ポエム','あああ',1);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('ハッシュ化','こじんかいはつー','(ほんとのnullではないです｡)','なし',2);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('Null(ほんとのnullではないです｡)','Null(ほんとのnullではないです｡)','Java','なし',3);
INSERT INTO memos(title,content,category,book_name,account_id) VALUES ('Undefined(ほんとのnullではないです｡)','JS','Javascript','なし',4);
